### ISSUE TITLE
Hardware prototyping

### ISSUE THREAD

**Issue by MDr164** [9elements/ProgressBar#1]
This is the umbrella issue for general discussions about the hardware design of the new Progress Bar panel. The plan for a rough design would include an ESP32 as the main MCU combined with a NFC/RFID scanner and potentially a small OLED Display.

**Proposal:**
- MCU: ESP32-C3
- NFC: NXP PN532 or ideally NXP PN7160
- OLED: ???

**TODO:**
Build a prototype design using e.g. a NodeMCU and breakout boards for the components

**HOW TO TEST:**
Very general functionality using example code

**Comment by PatrickRudolph** [comment]
**Missing:** Definition of a progress bar panel.
The following questions should be answered as part of the ticket description:
What is it used for?
Who should use it?
Where will it be deployed?
Does it need battery power or is it powered from a power outlet?
Does it need network connection?
The OLED implies that there's an UI. How is the user supposed to interact with the device?
Does it need to be water proof?
What's the expected power usage?
Does it need to idle a lot?
...

**Comment by MDr164** [comment]
Update with requested information (will eventually be added to the README once the repo is being filled):

Definition: Small Panel which can scan your RFID chip and register that you just bought a beer. This setup used to exist but was flawed. This endeavor is meant to revive the idea with a more bulletproof design.

What for: Register that a beverage is bought.

Who for: Employees using the ProgressBar.

Where: At the ProgressBar.

Power: Should be powered via 5V or 12V DC, no batteries planned.

Network: Yes, via WiFi (and potentially the Matter protocol)

Interaction: Only via holding the RFID chip to the scanner. The OLED might be used to display how many beverages are already registered to this chip upon scan.

Water proof: Not necessarily, but might be a good idea if feasible.

Power usage: Should not draw too much, but definite numbers don't exist yet.

Idle: Yes, it will idle quite a lot.
